name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Matches semantic version tags like v1.2.3

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish Crate
    permissions:
      id-token: write # Required for GitHub OIDC authentication
      contents: read  # Required by actions/checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Publish to crates.io
        run: cargo publish
